---
title: "About"
---

__Instructor__: <a href='https://www.gastonsanchez.com' target='_blank'>Gaston Sanchez</a>

__Lecture__: MWF 9am-10am in [Lewis Hall 100](https://www.berkeley.edu/map/lewis-hall/)

__Lab__:

- Lab 101, Th 9am-11am, Evans 342 (GSI TBD)
- Lab 102, Th 10am-12pm, Evans 340 (GSI TBD)
- Lab 103, Th 11am-1pm, Evans 342 (GSI TBD)
- Lab 104, Th 12pm-2pm, Evans 340 (GSI TBD)
- Lab 105, Th 1pm-3pm, Evans 342 (GSI TBD)
- Lab 106, Th 3pm-5pm, Evans 342 (GSI TBD)

__Prerequisites__: None

__Requirements__: Internet connection and a computer

__Code #__: 31203

__Units__: 3

__Final Exam__: Mon May-11th, 7pm-10pm, location TBD.

__Dates__: Jan-21 / May-01

-----

### Office Hours

Office hours are subject to change. You can attend OH of any staff member.
Append `@berkeley.edu` to all email addresses.

::: {.grid}

::: {.g-col-6}
**Instructor:** Gaston Sanchez<br>
`gastonsanchez`<br>
Office hours: <br>
- Day hh-hh, Evans 309<br>
:::

::: {.g-col-6}
**GSI**: Drew Galloro<br>
`arg2159`<br>
Office hours:<br>
- Day hh-hh, Evans TBD<br>
- Day hh-hh, Evans TBD
:::


::: {.g-col-6}
**GSI**: Clara Reckhorn<br>
`clara_reckhorn`<br>
Office hours: <br>
- Day hh-hh, Evans TBD<br>
- Day hh-hh, Evans TBD
:::

::: {.g-col-6}
**GSI:** William Torous<br>
`wtorous`<br>
Office hours: <br>
- Day hh-hh, Evans TBD<br>
- Day hh-hh, Evans TBD
:::


::: {.g-col-6}
**Tutor:** Carlota Blanco<br>
Office hours: <br>
- Day hh-hh, Evans TBD<br>
- Day hh-hh, Evans TBD
:::

::: {.g-col-6}
**Tutor**: Montserrat Ibarra<br>
Office hours: <br>
- Day hh-hh, Evans TBD<br>
- Day hh-hh, Evans TBD
:::

:::

