---
title: "STAT 133: Concepts in Computing with Data"
---

:::: {layout-ncol=4}
::: {.column width="10%"}
[Ed](https://edstem.org/us/courses/92259/discussion){.btn .btn-info role="button"}
:::

::: {.column width="15%"}
[bCourses](https://bcourses.berkeley.edu/courses/1551809){.btn .btn-primary role="button"}
:::

::: {.column width="25%"}
[R-DataHub](https://r.datahub.berkeley.edu/){.btn .btn-secondary role="button"}
:::

::: {.column width="50%"}
:::
::::

::: {.callout-tip icon="false"}
## Week 15 Announcements

- [Quiz 6]{.label-Quiz} due Thu 4/30 in lab
- [Project 6]{.label-Project} due Fri 5/01 by 6PM
:::

-----

:::: {layout-ncol=3}
::: {.column width="20%"}
#### Week 1
- Wed 1/21 

- [Thu 1/22]{.label-Labwork}

- Fri 1/23 
:::

::: {.column width="35%"}
#### Description
[Welcome](lectures/1-welcome/slides.html)

Lab 1: [slides](labs/lab1/slides.html)

[Introduction](lectures/2-intro/slides.html)
:::

::: {.column width="45%"}
#### Due

:::
::::

-----

:::: {layout-ncol=3}

::: {.column width="20%"}
#### Week 2
- Mon 1/26

- Wed 1/28

- [Thu 1/29]{.label-Labwork}

- Fri 1/30
:::

::: {.column width="35%"}
#### Description
[Vectors](lectures/3-atomic-vectors/slides.html)

[Working with Vectors](lectures/4-more-vectors/slides.html)

Lab 2: [slides](labs/lab2/slides.html) | [PS1](https://bcourses.berkeley.edu/courses/1551809/assignments/9021125)
 
[Unix Basics](lectures/5-unix-basics/slides.html) | [Proj1](https://bcourses.berkeley.edu/courses/1551809/assignments/9021606)
:::

::: {.column width="45%"}
#### Due
&nbsp;

&nbsp;

[Pub1]{.label-Pub}

&nbsp;
:::
::::


-----

:::: {layout-ncol=3}

::: {.column width="20%"}
#### Week 3
- Mon 2/2

- Wed 2/4 

- [Thu 2/5]{.label-Labwork}

- Fri 2/6 
:::

::: {.column width="35%"}
#### Description
[Extending Vectors](lectures/6-extending-vectors/slides.html)

[Lists](lectures/7-lists/slides.html)

Lab 3: [__Quiz 1__]{.label-Quiz} | [slides](labs/lab3/slides.html) | [PS2](https://bcourses.berkeley.edu/courses/1551809/assignments/9021126)

[Control Flow](lectures/8-control-flow/slides.html)
:::

::: {.column width="45%"}
#### Due
&nbsp;

[PS1]{.label-Homework}

[Pub2]{.label-Pub}

&nbsp;
:::
::::

-----

:::: {layout-ncol=3}

::: {.column width="20%"}
#### Week 4
- Mon 2/9

- Wed 2/11 

- [Thu 2/12]{.label-Labwork}

- Fri 2/13 
:::

::: {.column width="35%"}
#### Description
[Functions](lectures/9-functions/slides.html)

[Factors and Data Frames](lectures/10-factors/slides.html)

Lab 4: [slides](labs/lab4/slides.html) | [PS3](https://bcourses.berkeley.edu/courses/1551809/assignments/9021596)

[Data Wrangling I](lectures/11-data-wrangling1/slides.html) | [Proj2](https://bcourses.berkeley.edu/courses/1551809/assignments/9021607)
:::

::: {.column width="45%"}
#### Due
&nbsp;

[PS2]{.label-Homework}

[Pub3]{.label-Pub}

[Proj1]{.label-Project}
:::
::::

-----

:::: {layout-ncol=3}

::: {.column width="20%"}
#### Week 5
- [Mon 2/16]{.label-None}

- Wed 2/18 

- [Thu 2/19]{.label-Labwork}

- Fri 2/20
:::

::: {.column width="35%"}
#### Description
[No class]{.label-None}

[Data Wrangling II](lectures/12-data-wrangling2/slides.html)

Lab 5: [__Quiz 2__]{.label-Quiz} | [slides](labs/lab5/slides.html) | [PS4](https://bcourses.berkeley.edu/courses/1551809/assignments/9021597)

[Importing Tables](lectures/13-importing-tables/slides.html)
:::

::: {.column width="45%"}
#### Due
&nbsp;

[PS3]{.label-Homework}

[Pub4]{.label-Pub}

&nbsp;
:::
::::

-----

:::: {layout-ncol=3}

::: {.column width="20%"}
#### Week 6
- Mon 2/23

- Wed 2/25 

- [Thu 2/26]{.label-Labwork}

- Fri 2/27
:::

::: {.column width="35%"}
#### Description
[Dataviz I](lectures/14-dataviz1/slides.html)

[Dataviz II](lectures/15-dataviz2/slides.html)

Lab 6: [slides](labs/lab6/slides.html) | [PS5](https://bcourses.berkeley.edu/courses/1551809/assignments/9021598) 

[Dataviz III](lectures/16-dataviz3/slides.html) | [Proj3](https://bcourses.berkeley.edu/courses/1551809/assignments/9021608)
:::

::: {.column width="45%"}
#### Due
&nbsp;

[PS4]{.label-Homework}

[Pub5]{.label-Pub}

[Proj2]{.label-Project}
:::
::::

-----

:::: {layout-ncol=3}

::: {.column width="20%"}
#### Week 7
- Mon 3/2

- Wed 3/4 

- [Thu 3/5]{.label-Labwork}

- Fri 3/6
:::

::: {.column width="35%"}
#### Description
[Joins and Pivots](lectures/17-joins-pivots/slides.html)

[Exploratory EDA](lectures/18-eda1/slides.html)

Lab 7: [__Quiz 3__]{.label-Quiz} | [slides](labs/lab7/slides.html) | [PS6](https://bcourses.berkeley.edu/courses/1551809/assignments/9021599)

[Explanatory EDA](lectures/19-eda2/slides.html)
:::

::: {.column width="45%"}
#### Due
&nbsp;

[PS5]{.label-Homework}

[Pub6]{.label-Pub}

&nbsp;
:::
::::

-----

:::: {layout-ncol=3}

::: {.column width="20%"}
#### Week 8
- Mon 3/9

- Wed 3/11 

- [Thu 3/12]{.label-Labwork}

- Fri 3/13
:::

::: {.column width="35%"}
#### Description
[Strings I](lectures/20-strings1/slides.html)

[Strings II](lectures/21-strings2/slides.html)

Lab 8: [slides](labs/lab8/slides.html) | [PS7](https://bcourses.berkeley.edu/courses/1551809/assignments/9021600) 

[Strings III](lectures/22-strings3/slides.html) | [Proj4](https://bcourses.berkeley.edu/courses/1551809/assignments/9021609) 
:::

::: {.column width="45%"}
#### Due
&nbsp;

[PS6]{.label-Homework}

[Pub7]{.label-Pub}

[Proj3]{.label-Project}
:::
::::

-----

:::: {layout-ncol=3}

::: {.column width="20%"}
#### Week 9
- Mon 3/16

- Wed 3/18

- [Thu 3/19]{.label-Labwork}

- Fri 3/20
:::

::: {.column width="35%"}
#### Description
[Dates and Times I](lectures/23-date-time1/slides.html)

[Dates and Times II](lectures/24-date-time2/slides.html)

Lab 9: [__Quiz 4__]{.label-Quiz} | [slides](labs/lab9/slides.html) | [PS8](https://bcourses.berkeley.edu/courses/1551809/assignments/9021601)

[Dashboard Demo](lectures/25-date-time3/slides.html)
:::

::: {.column width="45%"}
#### Due
&nbsp;

[PS7]{.label-Homework}

[Pub8 canceled]{.label-Pub}

&nbsp;
:::
::::

-----

:::: {layout-ncol=2}

::: {.column width="20%"}
#### Week 10
- [3/23-3/27]{.label-None}
:::

::: {.column width="80%"}
#### Description
[Spring Recess]{.label-None}
:::

::::

-----

:::: {layout-ncol=3}

::: {.column width="20%"}
#### Week 11
- Mon 3/30

- Wed 4/1 

- [Thu 4/2]{.label-Labwork}

- Fri 4/3
:::

::: {.column width="35%"}
#### Description
[Shiny Dashboards I](lectures/26-shiny1/slides.html)

[Shiny Dashboards II](lectures/27-shiny2/slides.html)

Lab 10: [slides](labs/lab10/slides.html) | [PS9](https://bcourses.berkeley.edu/courses/1551809/assignments/9021602)

[Geospatial Data](lectures/28-geospatial1/slides.html) | [Proj5](https://bcourses.berkeley.edu/courses/1551809/assignments/9021610)
:::

::: {.column width="45%"}
#### Due
&nbsp;

[PS8]{.label-Homework}

[Pub9]{.label-Pub}

[Proj4]{.label-Project}
:::
::::

-----

:::: {layout-ncol=3}

::: {.column width="20%"}
#### Week 12
- Mon 4/6

- Wed 4/8

- [Thu 4/9]{.label-Labwork}

- Fri 4/10
:::

::: {.column width="35%"}
#### Description
[Mapping Storm tracks](lectures/29-geospatial2/slides.html)

[Leaflet Maps](lectures/30-geospatial3/slides.html)

Lab 11: [__Quiz 5__]{.label-Quiz} | [slides](labs/lab11/slides.html) | [PS10](https://bcourses.berkeley.edu/courses/1551809/assignments/9021603)

[Choropleth Maps](lectures/31-choropleth-maps/slides.html)
:::

::: {.column width="45%"}
#### Due
&nbsp;

[PS9]{.label-Homework}

[Pub10]{.label-Pub}

&nbsp;
:::
::::

-----

:::: {layout-ncol=3}

::: {.column width="20%"}
#### Week 13
- Mon 4/13

- Wed 4/15

- [Thu 4/16]{.label-Labwork}

- Fri 4/17
:::

::: {.column width="35%"}
#### Description
[Shapefiles](lectures/32-shapefiles/slides.html)

[Raster Data Maps](lectures/33-raster/slides.html)

Lab 12: [slides](labs/lab12/slides.html) | [PS11](https://bcourses.berkeley.edu/courses/1551809/assignments/9021604)

[Text Analysis 1](lectures/34-text-analysis1/slides.html) | Proj6
:::

::: {.column width="45%"}
#### Due
&nbsp;

[PS10]{.label-Homework}

[Pub11]{.label-Pub}

[Proj5]{.label-Project}
:::
::::

-----

:::: {layout-ncol=3}

::: {.column width="20%"}
#### Week 14
- Mon 4/20

- Wed 4/22

- [Thu 4/23]{.label-Labwork}

- Fri 4/24
:::

::: {.column width="35%"}
#### Description
[Text Analysis 2](lectures/35-text-analysis2/slides.html)

[Text Analysis 3](lectures/36-text-analysis3/slides.html)

[Lab 13: slides](labs/lab13/slides.html)

[JSON Data](lectures/37-json/slides.html)
:::

::: {.column width="45%"}
#### Due
&nbsp;

[PS11]{.label-Homework}

[Pub12]{.label-Pub}

&nbsp;
:::
::::

-----

:::: {layout-ncol=3}

::: {.column width="20%"}
#### Week 15
- Mon 4/27

- Wed 4/29

- [Thu 4/30]{.label-Labwork}

- Fri 5/1
:::

::: {.column width="35%"}
#### Description
[APIs I](lectures/38-apis1/slides.html)

APIs II

Lab 14: [__Quiz 6__]{.label-Quiz} | slides

Closing Lecture
:::

::: {.column width="45%"}
#### Due
&nbsp;

&nbsp;

&nbsp;

[Proj6]{.label-Project}
:::
::::

-----

:::: {layout-ncol=2}

::: {.column width="20%"}
#### Week 16
- [5/4-5/8]{.label-None}
:::

::: {.column width="80%"}
#### Description
[RRR Week]{.label-None}
:::

::::

-----

:::: {layout-ncol=2}

::: {.column width="20%"}
#### Week 17
- 5/11
:::

::: {.column width="80%"}
#### Description
[__Final Exam, 7-10pm__]{.label-Quiz}
:::

::::

-----





