---
title: "Lab 14"
subtitle: "Quiz 6"
author: "STAT 133"
format: stat133slides-revealjs
embed-resources: true
---

# Agenda

-   Announcements
-   Quiz 6
-   Project 6

## Announcements

-  Project 6 due this Friday at 6pm

-  Please fill out course evaluations (Professor and GSI) - they are very helpful to us

-  Review sessions during RRR week (MWF)

-  GSI office hours will continue as usual, Professor office hours TBD

# Before the Quiz

::: callout-important
A note on academic integrity:
:::

\
Cheating is **100% not tolerated**. Talking with other individuals during the quiz, using your phone for any reason, looking at others' answers, etc. will result in a violation of the Academic Integrity Pledge. We reserve the right to give a 0 to anyone seen cheating.

## Before the Quiz

::: nonincremental
1.  Spread out as much as possible.
2.  🚽 If you need to use the bathroom, this is the time to do it.
3.  🧹 Clear your desk of everything except a pen/pencil and your ID.
4.  🧢 Remove hats, hoods, and sunglasses (don't hide your face please!)
5.  📱 All electronic devices (laptop, phone, airbuds, smart watch) should remain in your bag for the entire quiz period.
:::

## Quiz {.smaller}

```{r}
countdown::countdown(35, top = 0)
```

::: nonincremental
1.  Please be quiet.
2.  When you get a quiz, do not begin until we tell you so.
3.  Write your name and SID.
4.  Keep your eyes on your own quiz.
5.  Only one person allowed to use the bathroom at a time.
6.  If you finish early, please hold on to your quiz and wait.
7.  When the timer ends, hold up your quiz in the air immediately and put your writing utensils down or risk a 0.
:::

Good luck! 🍀

# Project 6

Questions?

# Thanks for a great semester!

Best of luck on finals 😊